language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_script:
    - ls -l
    - chmod 777 mosbth/cimage/cache
    - chmod 777 mosbth/cimage/cache/dummy

script:
    - phpunit

notifications:
    irc: "irc.freenode.org#dbwebb"
