language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - "7.0"
    - "7.1"
    - hhvm
    - nightly



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck


matrix:
    allow_failures:
        - php: hhvm
        - php: nightly



before_script:
    - make install
    - make check



script:
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
          - https://webhooks.gitter.im/e/a89832db4f939e85ba97
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
